export const reasonsToReport = [
    'Hate speech or discriminatory language',
    'Violent or threatening content',
    'Harassment or bullying',
    'Graphic violence or gore',
    'Sexual content or nudity',
    'Impersonation or identity theft',
    'Spam or deceptive content',
    'Misinformation or fake news',
    'Intellectual property infringement',
    'Self-harm or suicide promotion',
    'Animal abuse or cruelty',
    'Child exploitation or abuse',
    "I just don't like it",
];
